language: android
jdk: oraclejdk8
env:
    matrix:
        - ANDROID_TARGET=android-23  ANDROID_ABI=google_apis/armeabi-v7a
android:
    components:
            - platform-tools
            - tools
            - build-tools-$ANDROID_BUILD_TOOLS_VERSION
            - extra-android-support
            # Latest artifacts in local repository
            - extra-google-m2repository
            - extra-android-m2repository

env:
  global:
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2

before_script:

    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest --stacktrace --info
notifications:
  slack: urlinq:LkEt5WeDyG3u34J7YwMik6ri
