language: android
jdk: oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-22.0.1
        - android-22
        - extra-google-google_play_services
        - extra
        - sys-img-armeabi-v7a-android-22
env:
  global:
    - ADB_INSTALL_TIMEOUT=10
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - android list target
  - ./gradlew connectedAndroidTest --stacktrace --info
notifications:
  email:
    recipients:
      - kaimou1357@gmail.com
  slack: urlinq:LkEt5WeDyG3u34J7YwMik6ri
